core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from core import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import MainView, PortfolioDetailsView, ServiceDetailsView
from django.views.generic import TemplateView

urlpatterns = [
    path('', MainView.as_view(), name='main'),
    path('portfolio-details/<int:pk>/', PortfolioDetailsView.as_view(), name='portfolio_details'),
    path('service-details/<int:pk>/', ServiceDetailsView.as_view(), name='service_details'),
    #path('protfolio-details/<int:pk>', TemplateView.as_view(template_name='main/portfolio-details.html'), name='portfolio_details')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class EducationItem(models.Model):
    name = models.CharField(max_length=255, null=True, blank=True)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    organization = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    certificate = models.ImageField(upload_to='certificates/', null=True, blank=True)
    
    class Meta:
        verbose_name = _('Education item')
        verbose_name_plural = _('Education items')
        ordering = ('end_date',)
    
    def __str__(self):
        return self.name


class PortfolioItem(models.Model):
    name = models.CharField(max_length=255, null=True, blank=True)
    category = models.CharField(max_length=10, choices=(('0', _("web")), ('1', _("app"))), null=True, blank=True)
    image = models.ImageField(upload_to='portfolio/', null=True, blank=True)
    project_date = models.DateField(null=True, blank=True)
    project_url = models.URLField(null=True, blank=True)
    client = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    
    class Meta:
        verbose_name = _('Portfolio item')
        verbose_name_plural = _('Portfolio items')
        ordering = ('name',)
    
    def __str__(self):
        return self.name


class PortfolioItemGallery(models.Model):
    item = models.ForeignKey(PortfolioItem, on_delete=models.CASCADE, related_name='portfolio_item')
    name = models.CharField(max_length=255, null=True, blank=True)
    image = models.ImageField(upload_to='portfolio/', null=True, blank=True)

    class Meta:
        verbose_name = _('Portfolio item gallery')
        verbose_name_plural = _('Portfolio item gallery')
        ordering = ('name',)

    def __str__(self):
        if self.name:
            return self.name
        else:
            return str(self.item)


class ServiceItem(models.Model):
    COLOR_CHOICES = (
        ('blue', 'Blue'),
        ('orange', 'Orange'),
        ('pink', 'Pink'),
        ('yellow', 'Yellow'),
        ('red', 'Red'),
        ('teal', 'Teal'),
    )

    DELAY_CHOICES = (
        ('100', '100'),
        ('200', '200'),
        ('300', '300'),
        ('400', '400'),
        ('500', '500'),
        ('600', '600'),
    )

    name = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        help_text=_("Name of the service"),
    )
    image = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        help_text=_("Presentation icon of the service (for example, 'bx bxl-dribbble')"),
    )
    color = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        choices=COLOR_CHOICES,
        default="blue",
        help_text=_("Background 'on hover' color of the service icon"),
    )
    svg_path = models.TextField(
        null=True,
        blank=True,
        help_text=_("SVG path <d> attribute"),
    )
    data_aos_delay = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        choices=DELAY_CHOICES,
        default="blue",
        help_text=_("Background 'on hover' color of the service icon"),
    )
    description = models.TextField(
        null=True,
        blank=True,
        help_text=_("Description of the service. HTML tags can be used for text format"),
    )
    full_description = models.TextField(
        null=True,
        blank=True,
        help_text=_("Full description of the service. HTML tags can be used for text format"),
    )

    class Meta:
        verbose_name = _('Service item')
        verbose_name_plural = _('Service items')
        ordering = ('name',)

    def __str__(self):
        return self.name


class ServiceItemGallery(models.Model):
    item = models.ForeignKey(
        ServiceItem,
        on_delete=models.CASCADE,
        related_name='service_item',
    )
    name = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        help_text=_("Name of the service details slider image"),
    )
    image = models.ImageField(
        upload_to='services/items/',
        null=True,
        blank=True,
        help_text=_("Image of the service details slider"),
    )

    class Meta:
        verbose_name = _('Service item gallery')
        verbose_name_plural = _('Service item gallery')
        ordering = ('name',)

    def __str__(self):
        if self.name:
            return self.name
        else:
            return str(self.item)


class ServiceItemClients(models.Model):
    item = models.ForeignKey(
        ServiceItem,
        on_delete=models.CASCADE,
        related_name='service_client',
    )
    name = models.CharField(
        max_length=1000,
        null=True,
        blank=True,
        help_text=_("Name of the client"),
    )
    image = models.ImageField(
        upload_to='services/clients/',
        null=True,
        blank=True,
        help_text=_("Logo image of the client"),
    )

    class Meta:
        verbose_name = _('Service item client')
        verbose_name_plural = _('Service item clients')
        ordering = ('name',)

    def __str__(self):
        if self.name:
            return self.name
        else:
            return str(self.item)

main/forms.py
from django import forms
from django.core.mail import EmailMessage
from django.utils.translation import gettext_lazy as _


class ContactForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField(max_length=200)
    subject = forms.CharField(max_length=200)
    message = forms.CharField(widget=forms.Textarea)
    
    def send_email(self):
        # send email using the self.cleaned_data dictionary
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        subject = self.cleaned_data['subject']
        message = f"Message from {name} <br> Email: {email} <br> Subject: {subject} <br> Message: { self.cleaned_data['message'] }"
        msg = EmailMessage(
                subject,
                message,
                email,
                ['contact@omorev.pp.ua', ],
            )
        msg.content_subtype = "html"
        msg.send()

main/views.py
from email.message import EmailMessage
from django.views.generic.edit import FormView
from django.views.generic import TemplateView, DetailView
from .forms import ContactForm
from .models import (
    EducationItem,
    PortfolioItem,
    PortfolioItemGallery,
    ServiceItem,
    ServiceItemGallery,
    ServiceItemClients
)
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.translation import gettext_lazy as _


class MainView(SuccessMessageMixin, FormView):
    template_name = 'main/main.html'
    form_class = ContactForm
    success_url = '#contact'
    success_message = _('The message was sent successfully')

    def get_context_data(self, **kwargs):
        context = super(MainView, self).get_context_data(**kwargs)
        context['education_items'] = EducationItem.objects.all().order_by("-end_date")
        context['portfolio_items'] = PortfolioItem.objects.all()
        context['service_items'] = ServiceItem.objects.all().order_by("id")
        return context

    def form_valid(self, form):
        form.send_email()
        return super().form_valid(form)


class PortfolioDetailsView(SuccessMessageMixin, DetailView):
    model = PortfolioItem
    template_name = 'main/portfolio-details.html'

    def get_context_data(self, **kwargs):
        context = super(PortfolioDetailsView, self).get_context_data(**kwargs)
        context['portfolio_item_gallery'] = PortfolioItemGallery.objects.filter(item_id=self.kwargs['pk'])
        return context


class ServiceDetailsView(SuccessMessageMixin, DetailView):
    model = ServiceItem
    template_name = 'main/service-details.html'

    def get_context_data(self, **kwargs):
        context = super(ServiceDetailsView, self).get_context_data(**kwargs)
        context['service_item_gallery'] = ServiceItemGallery.objects.filter(item_id=self.kwargs['pk'])
        context['service_item_clients'] = ServiceItemClients.objects.filter(item_id=self.kwargs['pk'])
        return context

templates/main/about.html
{% load i18n %}
{% load static %}

<!-- ======= About Section ======= -->
<section id="about" class="about">
	<div class="container" data-aos="fade-up">

		<div class="section-title">
			<h2>{% trans "About" %}</h2>
			<p>{% trans "Hard-working web developer with a flair for creating elegant solutions in the least amount of time. Developed customs web portal, number of webapps/scripts, customer web portal, telegram bots and automatic reports solutions. Passionate about software architecture and open data services. Regular attendee of web developer meetups and hackathons." %}</p>
		</div>

		<div class="row">
			<div class="col-lg-5">
				<img src="{% static 'img/profile-img.png' %}" class="img-fluid" alt="">
			</div>
			<div class="col-lg-7 pt-4 pt-lg-0 content">
				<h3>{% trans "Full-Stack Web Developer" %} &amp; {% trans "UI/UX Designer" %}</h3>
				<p class="fst-italic">
					{% trans "Development of web and desktop applications of varying complexity, content and implementation options, including those for working and administering databases, using modern frameworks, libraries and database management systems." %}
				</p>
				<div class="row">
					<div class="col-lg-6">
						<ul>
							<li><i class="bi bi-chevron-right"></i> <strong>{% trans "Website" %}:</strong> <span><a href="www.omorev.pp.ua">www.omorev.pp.ua</a></span</li>
							<li><i class="bi bi-chevron-right"></i> <strong>{% trans "Phone" %}:</strong> <span><a href="tel:+380672700861">+38 (067) 270 08 61</a></span</li>
							<li><i class="bi bi-chevron-right"></i> <strong>{% trans "City" %}:</strong> <span>{% trans "Bucha, Ukraine" %}</span></li>
						</ul>
					</div>
					<div class="col-lg-6">
						<ul>
							<li><i class="bi bi-chevron-right"></i> <strong>{% trans "Degree" %}:</strong> <span>{% trans "Master" %}</span></li>
							<li><i class="bi bi-chevron-right"></i> <strong>{% trans "Email" %}:</strong> <span><a href="mailto:contact@omorev.pp.ua">contact@omorev.pp.ua</a></span></li>
							<li><i class="bi bi-chevron-right"></i> <strong>{% trans "Freelance" %}:</strong> <span>{% trans "Available" %}</span></li>
							<li>
								<i class="bi bi-chevron-right"></i>
								<strong>{% trans "Visits" %}:</strong>
								<span>
									<div id="sfcxmqaf9aybqu24aa95ybkfyya6g2xq1qx"></div>
									<script type="text/javascript" src="https://counter9.stat.ovh/private/counter.js?c=xmqaf9aybqu24aa95ybkfyya6g2xq1qx&down=async" async></script>
									<noscript><a href="https://www.freecounterstat.com" title="free web counter html"><img src="https://counter9.stat.ovh/private/freecounterstat.php?c=xmqaf9aybqu24aa95ybkfyya6g2xq1qx" border="0" title="free web counter html" alt="free web counter html"></a></noscript>
								</span>
							</li>
						</ul>
					</div>
				</div>
				<p>
					{% trans "Experienced Web Developer with a proven history of working in the computer software industry. Skilled in Python, Django Framework, html5, javascript, jquery, telegram bot development, data analysis, web scraping, API and SQL. Strong and focused engineering professional completed Certification requirements and recognized as a Certified Associate in Python." %}
				</p>
			</div>
		</div>

	</div>
</section><!-- End About Section -->

templates/main/contact.html
{% load i18n %}
{% load static %}

<!-- ======= Contact Section ======= -->
<section id="contact" class="contact">
	<div class="container" data-aos="fade-up">

		<div class="section-title">
			<h2>{% trans "Contact" %}</h2>
		</div>

		<div class="row mt-1">

			<div class="col-lg-4">
				<div class="info">
					<div class="address">
						<i class="bi bi-geo-alt"></i>
						<h4>{% trans "Location" %}:</h4>
						<p>{% trans "Bucha, Kyiv region, Ukraine 08292" %}</p>
					</div>

					<div class="email">
						<i class="bi bi-envelope"></i>
						<h4>{% trans "Email" %}:</h4>
						<a href="mailto:contact@omorev.pp.ua">
							<p>contact@omorev.pp.ua</p>
						</a>
					</div>

					<div class="phone">
						<i class="bi bi-phone"></i>
						<h4>{% trans "Call" %}:</h4>
						<a href="tel:+380672700861">
						    <p>+38 067 2700861</p>
                        </a>
					</div>

				</div>

			</div>

			<div class="col-lg-8 mt-5 mt-lg-0">

				<form action="" method="post" role="form" class="php-email-form">
					{% csrf_token %}
					<div class="row">
						<div class="col-md-6 form-group">
							<input type="text" name="name" class="form-control" id="name" placeholder="Your Name" required>
						</div>
						<div class="col-md-6 form-group mt-3 mt-md-0">
							<input type="email" class="form-control" name="email" id="email" placeholder="Your Email" required>
						</div>
					</div>
					<div class="form-group mt-3">
						<input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" required>
					</div>
					<div class="form-group mt-3">
						<textarea class="form-control" name="message" rows="5" placeholder="Message" required></textarea>
					</div>
					<div class="my-3">
						<div class="loading">{% trans "Loading" %}</div>
						<div class="error-message"></div>
						<div class="sent-message">{% trans "Your message has been sent. Thank you!" %}</div>
					</div>
					<div class="text-center"><button type="submit">{% trans "Send Message" %}</button></div>
				</form>

			</div>

		</div>

	</div>
</section><!-- End Contact Section -->

templates/main/facts.html
{% load i18n %}
{% load static %}

<!-- ======= Facts Section ======= -->
<section id="facts" class="facts">
	<div class="container" data-aos="fade-up">

		<div class="section-title">
			<h2>{% trans "Facts" %}</h2>
			<p>{% trans "Results of work and achievements..." %}</p>
		</div>

		<div class="row">

			<div class="col-lg-3 col-md-6">
				<div class="count-box">
					<i class="bi bi-emoji-smile"></i>
					<span data-purecounter-start="0" data-purecounter-end="16" data-purecounter-duration="1" class="purecounter"></span>
					<p>{% trans "Happy Clients" %}</p>
				</div>
			</div>

			<div class="col-lg-3 col-md-6 mt-5 mt-md-0">
				<div class="count-box">
					<i class="bi bi-journal-richtext"></i>
					<span data-purecounter-start="0" data-purecounter-end="22" data-purecounter-duration="1" class="purecounter"></span>
					<p>{% trans "Projects" %}</p>
				</div>
			</div>

			<div class="col-lg-3 col-md-6 mt-5 mt-lg-0">
				<div class="count-box">
					<i class="bi bi-headset"></i>
					<span data-purecounter-start="0" data-purecounter-end="3020" data-purecounter-duration="1" class="purecounter"></span>
					<p>{% trans "Hours Of Support" %}</p>
				</div>
			</div>

			<div class="col-lg-3 col-md-6 mt-5 mt-lg-0">
				<div class="count-box">
					<i class="bi bi-award"></i>
					<span data-purecounter-start="0" data-purecounter-end="20" data-purecounter-duration="1" class="purecounter"></span>
					<p>{% trans "Certifications" %}</p>
				</div>
			</div>

		</div>

	</div>
</section><!-- End Facts Section -->

templates/main/hero.html
{% load i18n %}
{% load static %}

<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex flex-column justify-content-center">
	<div class="container" data-aos="zoom-in" data-aos-delay="100">
		<div>
			<img src="{% static 'img/logo_invert.png' %}" class="img-fluid" alt="">
		</div>
		<p>I'm <span class="typed" data-typed-items="Full-Stack Developer, Creative Designer, Freelancer"></span></p>
		<div class="social-links">
			<a href="mailto:contact@omorev.pp.ua" class="twitter"><i class="bx bx-mail-send"></i></a>
			{% comment %} <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a> {% endcomment %}
			<a href="https://t.me/morevag" class="facebook"><i class="bx bxl-telegram"></i></a>
			<a href="https://join.skype.com/invite/EDMiZcEvRbxn" class="facebook"><i class="bx bxl-skype"></i></a>
			<a href="https://www.facebook.com/agmorev/" class="facebook"><i class="bx bxl-facebook"></i></a>
			{% comment %} <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a> {% endcomment %}
			{% comment %} <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a> {% endcomment %}
			<a href="https://www.linkedin.com/in/aleksey-morev-168589241/" class="linkedin"><i class="bx bxl-linkedin"></i></a>
		</div>
	</div>
</section><!-- End Hero -->

templates/main/main.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
    
    <main id="main">

        {% include 'main/hero.html' %}
        
        {% include 'main/about.html' %}

        {% include 'main/facts.html' %}

        {% include 'main/skills.html' %}

        {% include 'main/resume.html' %}

        {% include 'main/portfolio.html' %}

        {% include 'main/services.html' %}

        {% comment %} {% include 'main/testimonials.html' %} {% endcomment %}

        {% include 'main/contact.html' %}

    </main><!-- End #main -->

{% endblock content %}

templates/main/portfolio-details.html
{% extends 'base.html' %}
{% load i18n %} 
{% load static %}


{% block header %}{% endblock header %}

{% block content %}

    <main id="main">

        <!-- ======= Portfolio Details Section ======= -->
        <section id="portfolio-details" class="portfolio-details">
            <div class="container">

                <div class="row gy-4">

                    <div class="col-lg-8">
                        <div class="portfolio-details-slider swiper">
                            <div class="swiper-wrapper align-items-center">
                                {% for slide in portfolio_item_gallery %}
                                    <div class="swiper-slide">
                                        <img src="{{ slide.image.url }}" alt="">
                                    </div>
                                {% endfor %}
                            </div>
                            <div class="swiper-pagination"></div>
                        </div>
                    </div>

                    <div class="col-lg-4">
                    <div class="portfolio-info">
                        <h3>{% trans "Project information" %}</h3>
                        <ul>
                            <li><strong>{% trans "Category" %}: </strong>{{ object.get_category_display|capfirst }}</li>
                            <li><strong>{% trans "Client" %}: </strong>{{ object.client }}</li>
                            <li><strong>{% trans "Project date" %}: </strong>{{ object.project_date }}</li>
                            <li><strong>{% trans "Project URL" %}: </strong>: <a href="{{ object.project_url }}">{{ object.project_url }}</a></li>
                        </ul>
                    </div>
                    <div class="portfolio-description">
                        <h2>{% trans "Description" %}:</h2>
                        <p>{{ object.description|safe }}</p>
                    </div>
                    </div>

                </div>

            </div>
        </section><!-- End Portfolio Details Section -->

    </main><!-- End #main -->

{% endblock content %}

{% block footer %}{% endblock footer %}

templates/main/portfolio.html
{% load i18n %}
{% load static %}

<!-- ======= Portfolio Section ======= -->
<section id="portfolio" class="portfolio section-bg">
    <div class="container" data-aos="fade-up">

        <div class="section-title">
            <h2>{% trans "Portfolio" %}</h2>
            <p>{% trans "Some of my projects that have been developed using different technologies and frameworks" %}</p>
        </div>

        <div class="row">
            <div class="col-lg-12 d-flex justify-content-center" data-aos="fade-up" data-aos-delay="100">
                <ul id="portfolio-flters">
                    <li data-filter="*" class="filter-active">{% trans "All" %}</li>
                    <li data-filter=".filter-web">{% trans "Web" %}</li>
                    <li data-filter=".filter-app">{% trans "App" %}</li>
                </ul>
            </div>
        </div>

        <div class="row portfolio-container" data-aos="fade-up" data-aos-delay="200">

            {% for item in portfolio_items %}
                <div class="col-lg-4 col-md-6 portfolio-item filter-{{ item.get_category_display }}">
                    <div class="portfolio-wrap">
                        <img src="{{ item.image.url }}" class="img-fluid" alt="">
                        <div class="portfolio-info">
                            <h4>{{ item.name|capfirst }}</h4>
                            <p>{{ item.get_category_display|capfirst }}</p>
                            <div class="portfolio-links">
                                <a href="{{ item.image.url }}" data-gallery="portfolioGallery" class="portfolio-lightbox" title="App 1"><i class="bx bx-plus"></i></a>
                                <a href="{% url 'portfolio_details' pk=item.id %}" class="portfolio-details-lightbox" data-glightbox="type: external" title="Portfolio Details"><i class="bx bx-link"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}

        </div>

    </div>
</section>
<!-- End Portfolio Section -->

templates/main/resume.html
{% load i18n %}
{% load static %}

<!-- ======= Resume Section ======= -->
<section id="resume" class="resume">
    <div class="container" data-aos="fade-up">

        <div class="section-title">
            <h2>{% trans "Resume" %}</h2>
            <p>{% trans "Software developer specializes in creating, implementing and maintaining software and databases. Here are my educational and professional background:" %}</p>
        </div>

        <div class="row">
            <div class="col-lg-6">
                <h3 class="resume-title">{% trans "Sumary" %}</h3>
                <div class="resume-item pb-0">
                    <h4>{% trans "Oleksii Morev" %}</h4>
                    <p><em>{% trans "Proficient in various platforms, languages, and embedded systems. Experienced with cutting-edge development tools and procedures. Able to effectively self-manage during independent projects, as well as collaborate as part of a productive team." %}</em></p>
                    <ul>
                        <li>{% trans "Bucha, 08292 Ukraine" %}</li>
                        <li><a href="tel:+380672700861">+38 (067) 270 08 61</a></li>
                        <li><a href="mailto:office@omorev.pp.ua">office@omorev.pp.ua</a></li>
                    </ul>
                </div>

                <h3 class="resume-title">{% trans "Education" %}</h3>

                {% for item in education_items %}
                    <div class="resume-item">
                        <h4>{% trans item.name %}</h4>
                        <h5>{{ item.start_date|date:"M Y" }}{% if item.start_date and item.end_date %} - {% endif %}{{ item.end_date|date:"M Y" }}</h5>
                        <p><em>{{ item.organization|capfirst }}</em></p>
                    </div>
                {% endfor %}

            </div>
            <div class="col-lg-6">
                <h3 class="resume-title">{% trans "Professional Experience" %}</h3>
                <div class="resume-item">
                    <h4>{% trans "Python Developer" %}</h4>
                    <h5>2022 - Present</h5>
                    <p><em>QUALITY AREA LIMITED, Malta</em></p>
                    <p><em>LINK DIGITAL, Australia</em></p>
                    <ul>
                        <li>{% trans "Development of the world's leading Open Source data portal platform CKAN" %}</li>
                    </ul>
                </div>
                <div class="resume-item">
                    <h4>{% trans "Deputy Head" %}</h4>
                    <h5>2020 - 2022</h5>
                    <p><em>PENTADA TRANS FP, Kyiv, Ukraine</em></p>
                    <ul>
                        <li>{% trans "Full stack online client office using Python Web Frameworks (Django, Flask, FastAPI), SQL (MySQL, PostgreSQL, SQLite), Pandas, Javascript and jQuery, HTML, Bootstrap, CSS (SCSS)" %}</li>
                        <li>{% trans "Developed a large number of python scripts, including using web-scraping technologies, working with third-party databases, including through the API in order to optimize, simplify and speed up a number of processes and procedures in company interaction with customers, customs authorities and automatical ensure the company's management with real time analytics and statistics" %}</li>
                        <li>{% trans "Developed a powerful comprehensive multi-level Telegram bot (aiogram library), aimed at comfortable interaction with the client, providing him with the necessary current information from third-party resources, various calculators in the customs sphere, database data, reporting on work, access to additional functionality in personal office in the bot, interaction with corporate chats" %}</li>
                        <li>{% trans "Startup to develop a web portal for interaction of individuals and legal entities with customs authorities" %}</li>
                    </ul>
                </div>
                <div class="resume-item">
                    <h4>{% trans "Customs Officer" %}</h4>
                    <h5>2002 - 2020</h5>
                    <p><em>STATE CUSTOMS SERVICE OF UKRAINE</em></p>
                    <ul>
                        <li>{% trans "Worked on different positions: inspector, deputy head of customs offices, head of department in the central office. Main duties: all kind of works (control, enforcement, risks analyzing, payments, legislation, etc.) concerning customs control and customs clearance of goods" %}</li>
                    </ul>
                </div>
            </div>
        </div>

    </div>
</section><!-- End Resume Section -->

templates/main/service-details.html
{% extends 'base.html' %}
{% load i18n %} 
{% load static %}


{% block header %}{% endblock header %}

{% block content %}

    <main id="main">

        <!-- ======= Service Details Section ======= -->
        <section id="portfolio-details" class="portfolio-details">
            <div class="container">

                <div class="row gy-10">

                    <div class="col-lg-8">
                        <div class="portfolio-details-slider swiper">
                            <div class="swiper-wrapper align-items-center">
                                {% for slide in service_item_gallery %}
                                    <div class="swiper-slide">
                                        <img src="{{ slide.image.url }}" alt="">
                                    </div>
                                {% endfor %}
                            </div>
                            <div class="swiper-pagination"></div>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="portfolio-info">
                            <h3>{% trans "Service information" %}</h3>
                            <ul>
                                <li><strong>{% trans "Name" %}: </strong>{{ object.name|upper }}</li>
                            </ul>
                        </div>
                        <div class="portfolio-description">
                            <h2>{% trans "Description" %}:</h2>
                            <p>{{ object.full_description }}</p>
                        </div>
                    </div>

                </div>

            </div>
        </section><!-- End Service Details Section -->

    </main><!-- End #main -->

{% endblock content %}

{% block footer %}{% endblock footer %}

templates/main/services.html
{% load i18n %}
{% load static %}

<!-- ======= Services Section ======= -->
<section id="services" class="services">
    <div class="container" data-aos="fade-up">

        <div class="section-title">
            <h2>{% trans "Services" %}</h2>
            <p>
                {% trans "The quality of the work is guaranteed by the professional qualities, the use of the applied information technologies, the work organization process, and the regular feedback sessions with clients." %}
            </p>
        </div>

        <div class="row">

            {% for item in service_items %}
                <div class="col-lg-4 col-md-6 d-flex align-items-stretch" data-aos="zoom-in" data-aos-delay="{{ item.data_aos_delay }}">
                    {% comment %} <a href="{% url 'service_details' pk=item.id %}" class="portfolio-details-lightbox" data-glightbox="type: external" title="Service Details"> {% endcomment %}
                        <div class="icon-box iconbox-{{ item.color }}">
                            <div class="icon">
                                <svg width="100" height="100" viewBox="0 0 600 600" xmlns="http://www.w3.org/2000/svg">
                                    <path stroke="none" stroke-width="0" fill="#f5f5f5" d="{{ item.svg_path }}"></path>
                                </svg>
                                <i class="{{ item.image }}"></i>
                            </div>
                            <h4><a href="">{{ item.name|upper }}</a></h4>
                            <p>{{ item.description|safe }}</p>
                        </div>
                    {% comment %} </a> {% endcomment %}
                </div>
            {% endfor %}

        </div>

    </div>
</section><!-- End Services Section -->